<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Accountsection_2024 extends Model
{
    use HasFactory;
    protected $table ='accountsection_2024';
    protected $primaryKey ='id';
    protected $fillable = [
            'title',            
            'membership', 
            'full', 
            'first', 
            'family', 
            'insurer', 
            'cover', 
            'product_type', 
            'payment', 
            'policy', 
            'country_nationality', 
            'country_residence', 
            'gender', 
            'birthday', 
            'age', 
            'group_name', 
            'group_number', 
            'group_identifier',
            'type_applicant', 
            'main_applicant_deps', 
            'original_date', 
            'start_date', 
            'end_date', 
            'cancelled_date', 
            'contact_number', 
            'applicant_email_address', 
            'email_address', 
            'subscription_currency', 
            'mode_payment', 
            'payment_frequency', 
            'pro_rated_premium', 
            'premium', 
            'active_premium', 
            'frequency_premium', 
            'case_closed', 
            'residence', 
            'mailing_address',
            'renewal_date', 
            'case_officer', 
            'placement_done', 
            'placement_date', 
            'account', 
            'account_code', 
            'percentage_commission',             
            'source_inquiry', 
            'sub_agents_name', 
            'sub_agent_percentage', 
            'commission_paid', 
            'referral_name', 
            'website', 
            'referral_percentage', 
            'net_commission', 
            'estimated_premium', 
            'convert_premium_USD', 
            'placement_date2', 
            'credentials', 
            'dental', 
            'maternity', 
            'room_discount', 
            'direct_billing', 
            'bc14', 
            'area_cover', 
            'application_email', 
            'confirmation_email', 
            'invoice', 
            'payment_status', 
            'payment_follow', 
            'remarks', 
            'lives_2024', 
            'commission_2024', 
            'start_2024', 
            'commission_paid_sub_2024',
            'encoded_by',  
            'percentage_loading_2024', 
            'company_product_discount', 
            'renewal_discount_2024',
            'further_discount', 
            'total_members_2024', 
            'case_officer_2024', 
            'renewal_follow_up', 
            'payment_date_subagents_commission', 
            'status', 
            'missing_remarks',
            'cancelled_remarks',
            'secondary_personal_email',
            'secondary_contact_person_email',
            'secondary_contact_number',
            'updated_by',
            'medical818_prem_account',
            'medical818_prem_account_USD',
            'medical818_admin',
            'insurance_type',
            'attachment',
            'attachment_2',
            'attachment_3',
            'renewal_status',
            'renewal_premium',
            'renewal_commission',
            'convert_premium_USD_renewal'
    ];
    // In Accountsection_2024 model
public function claims()
{
    return $this->hasMany(Claim::class, 'complete_name', 'full');
}
}
