<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Accountsection extends Model
{
    use HasFactory;
    protected $table ='accountsection';
    protected $primaryKey ='id';
    protected $fillable = [
            'title',
            'compliance',
            'membership',
            'full',
            'first',
            'family',
            'insurer',
            'cover',
            'product_type',
            'payment',
            'policy',
            'country_nationality',
            'country_residence',
            'gender',
            'birthday',
            'age',
            'group_name',
            'group_number',
            'type_applicant',
            'main_applicant_deps',
            'original_date',
            'start_date',
            'end_date',
            'cancelled_date',
            'months',
            'contact_number',
            'applicant_email_address',
            'email_address',
            'subscription_currency',
            'mode_payment',
            'payment_frequency',
            'pro_rated_premium',
            'premium',
            'active_premium',
            'active_premium_not_paid',
            'frequency_premium',
            'case_closed',
            'residence',
            'mailing_address',
            'renewal_month',
            'renewal_year',
            'renewal_date',
            'case_officer',
            'placement_done',
            'placement_date',
            'account',
            'account_code',
            'percentage_commission',
            'commission_received',
            'commission_received_in_USD',
            'bank_account_commission',
            'confirmation_commission_received',
            'commission_discount',
            'source_inquiry',
            'sub_agents_name',
            'sub_agent_percentage',
            'commission_paid',
           'referral_name',
            'website',
            'referral_percentage',
            'net_commission',
            'estimated_premium',
            'convert_premium_USD',
            'placement_date2',
            'credentials',
            'dental',
            'maternity',
            'room_discount',
            'direct_billing',
            'bc14',
            'area_cover',
            'application_email',
            'confirmation_email',
            'invoice',
            'payment_status',
            'payment_follow',
            'ccdc',
            'ccn',
            'cc_holder_name',
            'relationship',
            'cc_exp',
            'vvc',
            'issuing_bank',
            'bank_account',
            'running_date',
            'remarks',
            'lives_2022',
            'commission_2022',
            'start_2022',
            'commission_paid_sub_2022',
            'encoded_by',
            'if_there_is_loading',
            'percentage_loading_2022',
            'company_product_discount',
            'renewal_discount_2022',
            'further_discount',
            'total_members_2022',
            'case_officer_2022',
            'renewal_follow_up',
            'payment_date_subagents_commission',
            'status',
            'missing_remarks',
            'cancelled_remarks',
            'secondary_personal_email',
            'secondary_contact_person_email',
            'secondary_contact_number',
            'updated_by'
    ];
    
}
